export const COUNTRIES = {
  Afghanistan: ["Badakhshan", "Kabul", "Herat", "Kandahar", "Ghazni"],
  Albania: ["Tiranë", "Shkodër", "Dibër", "Vlorë", "Fier"],
  Algeria: ["Algiers", "Oran", "Constantine", "Blida", "Annaba"],
  Argentina: ["Buenos Aires", "Córdoba", "Mendoza", "Santa Fe", "Tucumán"],
  Armenia: ["Yerevan", "Kotayk", "Lori", "Shirak", "Syunik"],
  Australia: [
    "New South Wales",
    "Queensland",
    "Victoria",
    "South Australia",
    "Western Australia",
  ],
  Austria: ["Vienna", "Salzburg", "Tyrol", "Styria", "Upper Austria"],
  Azerbaijan: ["Baku", "Ganja", "Mingachevir", "Sumqayit", "Lankaran"],
  Bahamas: ["New Providence", "Grand Bahama", "Abaco", "Bimini", "Exuma"],
  Bahrain: ["Capital", "Muharraq", "Northern", "Southern", "Islands"],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  Barbados: [
    "Saint Michael",
    "Christ Church",
    "Saint George",
    "Saint James",
    "Saint Lucy",
  ],
  Belarus: ["Minsk", "Gomel", "Brest", "Vitebsk", "Grodno"],
  Belgium: ["Brussels", "Antwerp", "East Flanders", "West Flanders", "Liege"],
  Belize: ["Cayo", "Belize", "Toledo", "Orange Walk", "Corozal"],
  Benin: ["Cotonou", "Porto-Novo", "Alibori", "Borgou", "Donga"],
  Bhutan: ["Thimphu", "Paro", "Chukha", "Samdrup Jongkhar", "Bumthang"],
  Bolivia: ["La Paz", "Santa Cruz", "Cochabamba", "Potosí", "Tarija"],
  "Bosnia and Herzegovina": [
    "Sarajevo",
    "Tuzla",
    "Zenica",
    "Mostar",
    "Banja Luka",
  ],
  Botswana: ["Gaborone", "Francistown", "Molepolole", "Maun", "Selibe Phikwe"],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Bahia",
    "Minas Gerais",
    "Pernambuco",
  ],
  Brunei: ["Brunei-Muara", "Belait", "Temburong", "Tutong", "Pekan"],
  Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
  "Burkina Faso": [
    "Ouagadougou",
    "Bobo-Dioulasso",
    "Koudougou",
    "Banfora",
    "Kaya",
  ],
  Burundi: ["Bujumbura", "Gitega", "Muyinga", "Ngozi", "Makamba"],
  Cambodia: [
    "Phnom Penh",
    "Siem Reap",
    "Sihanoukville",
    "Battambang",
    "Kampong Cham",
  ],
  Cameroon: ["Yaoundé", "Douala", "Bafoussam", "Garoua", "Bertoua"],
  Canada: ["Ontario", "Quebec", "British Columbia", "Alberta", "Nova Scotia"],
  "Central African Republic": [
    "Bangui",
    "Bamingui-Bangoran",
    "Ouham",
    "Sangha-Mbaéré",
    "Vakaga",
  ],
  Chad: ["N'Djamena", "Moundou", "Abéché", "Sarh", "Kélo"],
  Chile: ["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Temuco"],
  China: ["Beijing", "Shanghai", "Guangdong", "Shandong", "Jiangsu"],
  Colombia: [
    "Bogotá",
    "Antioquia",
    "Valle del Cauca",
    "Atlántico",
    "Cundinamarca",
  ],
  Comoros: ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Dzaoudzi"],
  Congo: ["Brazzaville", "Pointe-Noire", "Brazaville", "Kouilou", "Bouenza"],
  "Costa Rica": ["San José", "Alajuela", "Cartago", "Heredia", "Guanacaste"],
  Croatia: ["Zagreb", "Split", "Dubrovnik", "Osijek", "Rijeka"],
  Cuba: ["Havana", "Pinar del Río", "Matanzas", "Cienfuegos", "Camagüey"],
  Cyprus: ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos"],
  Czechia: ["Prague", "Brno", "Plzeň", "Ostrava", "Liberec"],
  Denmark: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  Djibouti: ["Djibouti City", "Ali Sabieh", "Tadjourah", "Arta", "Dikhil"],
  Dominica: ["Roseau", "Portsmouth", "Marigot", "Saint Joseph", "Grand Bay"],
  "Dominican Republic": [
    "Santo Domingo",
    "Santiago",
    "La Vega",
    "San Cristóbal",
    "San Pedro de Macorís",
  ],
  Ecuador: ["Quito", "Guayaquil", "Cuenca", "Ambato", "Machala"],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan"],
  "El Salvador": [
    "San Salvador",
    "Santa Ana",
    "San Miguel",
    "Ahuachapán",
    "Sonsonate",
  ],
  "Equatorial Guinea": ["Malabo", "Bata", "Ebebiyin", "Aconibe", "Luba"],
  Eritrea: ["Asmara", "Keren", "Massawa", "Mendefera", "Dekemhare"],
  Estonia: ["Tallinn", "Tartu", "Pärnu", "Narva", "Jõhvi"],
  Eswatini: ["Mbabane", "Manzini", "Lobamba", "Nhlangano", "Piggs Peak"],
  Ethiopia: ["Addis Ababa", "Oromia", "Amhara", "Tigray", "SNNPR"],
  Fiji: ["Suva", "Nadi", "Lautoka", "Labasa", "Ba"],
  Finland: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  France: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  Gabon: ["Libreville", "Port-Gentil", "Franceville", "Moanda", "Koulamoutou"],
  Gambia: ["Banjul", "Serrekunda", "Brikama", "Bakau", "Mansa Konko"],
  Georgia: ["Tbilisi", "Batumi", "Kutaisi", "Zugdidi", "Rustavi"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne"],
  Ghana: ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast"],
  Greece: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  Grenada: ["St. George's", "St. David", "St. Andrew", "St. Mark", "St. John"],
  Guatemala: [
    "Guatemala City",
    "Antigua Guatemala",
    "Escuintla",
    "Quetzaltenango",
    "Chimaltenango",
  ],
  Guinea: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Faranah"],
  "Guinea-Bissau": ["Bissau", "Biombo", "Cacheu", "Gabu", "Oio"],
  Guyana: [
    "Georgetown",
    "Essequibo Islands",
    "Demerara-Mahaica",
    "Berbice",
    "Pomeroon-Supenaam",
  ],
  Haiti: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Jacmel", "Les Cayes"],
  Honduras: [
    "Tegucigalpa",
    "San Pedro Sula",
    "La Ceiba",
    "Choluteca",
    "Comayagua",
  ],
  Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  Iceland: [
    "Reykjavik",
    "Akureyri",
    "Reykjanesbær",
    "Kopavogur",
    "Hafnarfjordur",
  ],
  India: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Lakshadweep",
    "Delhi",
    "Puducherry",
  ],
  Indonesia: ["Jakarta", "Bali", "Surabaya", "Bandung", "Yogyakarta"],
  Iran: ["Tehran", "Mashhad", "Isfahan", "Shiraz", "Tabriz"],
  Iraq: ["Baghdad", "Mosul", "Basra", "Erbil", "Sulaymaniyah"],
  Ireland: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  Israel: ["Tel Aviv", "Jerusalem", "Haifa", "Eilat", "Be'er Sheva"],
  Italy: ["Rome", "Milan", "Naples", "Florence", "Venice"],
  Jamaica: [
    "Kingston",
    "Montego Bay",
    "Spanish Town",
    "Mandeville",
    "Ocho Rios",
  ],
  Japan: ["Tokyo", "Osaka", "Kyoto", "Sapporo", "Fukuoka"],
  Jordan: ["Amman", "Zarqa", "Irbid", "Aqaba", "Mafraq"],
  Kazakhstan: ["Almaty", "Astana", "Shymkent", "Karaganda", "Aktobe"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  Kiribati: ["South Tarawa", "Betio", "Bairiki", "Nikunau", "Onotoa"],
  "Korea, North": ["Pyongyang", "Nampo", "Hamhung", "Chongjin", "Sinuiju"],
  "Korea, South": ["Seoul", "Busan", "Incheon", "Daegu", "Gwangju"],
  Kuwait: [
    "Kuwait City",
    "Al Ahmadi",
    "Al Farwaniyah",
    "Hawalli",
    "Mubarak Al Kabeer",
  ],
  Kyrgyzstan: ["Bishkek", "Osh", "Jalal-Abad", "Batken", "Issyk-Kul"],
  Laos: [
    "Vientiane",
    "Luang Prabang",
    "Savannakhet",
    "Champasak",
    "Xieng Khouang",
  ],
  Latvia: ["Riga", "Jurmala", "Liepaja", "Jelgava", "Daugavpils"],
  Lebanon: [
    "Beirut",
    "Mount Lebanon",
    "North Governorate",
    "South Governorate",
    "Beqaa",
  ],
  Lesotho: ["Maseru", "Berea", "Butha-Buthe", "Leribe", "Mafeteng"],
  Liberia: ["Monrovia", "Grand Bassa", "Nimba", "Bong", "Margibi"],
  Libya: ["Tripoli", "Benghazi", "Misrata", "Al Khums", "Zliten"],
  Liechtenstein: ["Vaduz", "Balzers", "Eschen", "Schaan", "Balzers"],
  Lithuania: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  Luxembourg: [
    "Luxembourg City",
    "Ettelbruck",
    "Ettelbruck",
    "Diekirch",
    "Grevenmacher",
  ],
  Madagascar: [
    "Antananarivo",
    "Toamasina",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
  ],
  Malawi: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
  Malaysia: ["Kuala Lumpur", "Selangor", "Penang", "Johor", "Sabah"],
  Maldives: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Hinnavaru"],
  Mali: ["Bamako", "Ségou", "Koulikoro", "Mopti", "Kayes"],
  Malta: ["Valletta", "Mosta", "Mġarr", "Birkirkara", "Sliema"],
  "Marshall Islands": [
    "Majuro",
    "Ebeye",
    "Kwajalein",
    "Arno Atoll",
    "Bikini Atoll",
  ],
  Mauritania: ["Nouakchott", "Nouadhibou", "Rosso", "Kaédi", "Atar"],
  Mauritius: [
    "Port Louis",
    "Beau Bassin-Rose Hill",
    "Curepipe",
    "Vacoas-Phoenix",
    "Quatre Bornes",
  ],
  Mexico: ["CDMX", "Jalisco", "Nuevo León", "Chihuahua", "Veracruz"],
  Micronesia: ["Palikir", "Colonia", "Weno", "Pohnpei", "Yap"],
  Moldova: ["Chisinau", "Bălți", "Tiraspol", "Bender", "Briceni"],
  Monaco: [
    "Monaco",
    "La Condamine",
    "Moneghetti",
    "Fontvieille",
    "Monte Carlo",
  ],
  Mongolia: ["Ulaanbaatar", "Darkhan", "Erdenet", "Mörön", "Choibalsan"],
  Montenegro: [
    "Podgorica",
    "Nikšić",
    "Herceg Novi",
    "Bijelo Polje",
    "Pljevlja",
  ],
  Morocco: ["Rabat", "Casablanca", "Marrakesh", "Fes", "Tangier"],
  Mozambique: ["Maputo", "Beira", "Nampula", "Chimoio", "Nacala"],
  Myanmar: ["Yangon", "Mandalay", "Naypyidaw", "Bago", "Sagaing"],
  Namibia: ["Windhoek", "Swakopmund", "Walvis Bay", "Rehoboth", "Grootfontein"],
  Nauru: ["Yaren", "Boe", "Denigomodu", "Anabar", "Ewa"],
  Nepal: ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Dunedin",
  ],
  Nicaragua: ["Managua", "León", "Masaya", "Chinandega", "Estelí"],
  Niger: ["Niamey", "Maradi", "Zinder", "Tahoua", "Agadez"],
  Nigeria: ["Lagos", "Abuja", "Rivers", "Kano", "Ogun"],
  "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Ohrid"],
  Norway: ["Oslo", "Bergen", "Stavanger", "Trondheim", "Drammen"],
  Oman: ["Muscat", "Salalah", "Sohar", "Nizwa", "Ibri"],
  Pakistan: [
    "Islamabad",
    "Punjab",
    "Sindh",
    "Khyber Pakhtunkhwa",
    "Balochistan",
  ],
  Palau: ["Ngerulmud", "Koror", "Melekeok", "Airai", "Ngaraard"],
  Panama: ["Panama City", "Colón", "David", "La Chorrera", "Santiago"],
  "Papua New Guinea": [
    "Port Moresby",
    "Lae",
    "Mount Hagen",
    "Madang",
    "Rabaul",
  ],
  Paraguay: [
    "Asunción",
    "Ciudad del Este",
    "Encarnación",
    "Pedro Juan Caballero",
    "Concepción",
  ],
  Peru: ["Lima", "Arequipa", "Cusco", "Trujillo", "Chiclayo"],
  Philippines: ["Manila", "Quezon City", "Cebu", "Davao", "Makati"],
  Poland: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Poznań"],
  Portugal: ["Lisbon", "Porto", "Amadora", "Braga", "Coimbra"],
  Qatar: ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Al Daayen"],
  Romania: ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  Russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Nizhny Novgorod",
  ],
  Rwanda: ["Kigali", "Butare", "Gisenyi", "Kibuye", "Musanze"],
  "Saint Kitts and Nevis": [
    "Basseterre",
    "Charlestown",
    "Sandy Point Town",
    "Newcastle",
    "Cayon",
  ],
  "Saint Lucia": [
    "Castries",
    "Gros Islet",
    "Vieux Fort",
    "Soufrière",
    "Dennery",
  ],
  "Saint Vincent and the Grenadines": [
    "Kingstown",
    "Bequia",
    "Union Island",
    "Mustique",
    "Canouan",
  ],
  Samoa: ["Apia", "Faleasi'u", "Lufilufi", "Salelologa", "Leulumoega"],
  "San Marino": [
    "San Marino",
    "Serravalle",
    "Borgo Maggiore",
    "Faetano",
    "Montegiardino",
  ],
  "Sao Tome and Principe": [
    "São Tomé",
    "Santo Amaro",
    "Trindade",
    "Neves",
    "Caixão Grande",
  ],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  Senegal: ["Dakar", "Saint-Louis", "Kaolack", "Ziguinchor", "Tambacounda"],
  Serbia: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  Seychelles: [
    "Victoria",
    "Beau Vallon",
    "Anse Royale",
    "Grand Anse",
    "Port Glaud",
  ],
  "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
  Singapore: ["Central", "North", "North-East", "East", "West"],
  Slovakia: ["Bratislava", "Košice", "Prešov", "Nitra", "Trnava"],
  Slovenia: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  "Solomon Islands": [
    "Honiara",
    "Malaita",
    "Guadalcanal",
    "Makira",
    "Choiseul",
  ],
  Somalia: ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Baidoa"],
  "South Africa": [
    "Pretoria",
    "Cape Town",
    "Durban",
    "Port Elizabeth",
    "Bloemfontein",
  ],
  "South Sudan": ["Juba", "Wau", "Malakal", "Aweil", "Rumbek"],
  Spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Anuradhapura"],
  Sudan: ["Khartoum", "Omdurman", "Nyala", "Port Sudan", "El Fasher"],
  Suriname: [
    "Paramaribo",
    "Lelydorp",
    "Nieuw Nickerie",
    "Moengo",
    "Marienburg",
  ],
  Sweden: ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås"],
  Switzerland: ["Zurich", "Geneva", "Bern", "Basel", "Lucerne"],
  Syria: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"],
  Taiwan: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan"],
  Tajikistan: ["Dushanbe", "Khujand", "Kulob", "Bokhtar", "Istaravshan"],
  Tanzania: ["Dodoma", "Dar es Salaam", "Mwanza", "Arusha", "Mbeya"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Nakhon Ratchasima"],
  "Timor-Leste": ["Dili", "Baucau", "Viqueque", "Suai", "Maliana"],
  Togo: ["Lomé", "Sokodé", "Kara", "Atakpamé", "Kpalimé"],
  Tonga: ["Nuku'alofa", "Vava'u", "Ha'apai", "Eua", "Niuafo'ou"],
  "Trinidad and Tobago": [
    "Port of Spain",
    "San Fernando",
    "Scarborough",
    "Chaguanas",
    "Arima",
  ],
  Tunisia: ["Tunis", "Sfax", "Sousse", "Kairouan", "Gabès"],
  Turkey: ["Ankara", "Istanbul", "Izmir", "Bursa", "Antalya"],
  Turkmenistan: ["Ashgabat", "Turkmenbashi", "Mary", "Dashoguz", "Lebap"],
  Tuvalu: ["Funafuti", "Nanumea", "Nanumaga", "Nui", "Vaitupu"],
  Uganda: ["Kampala", "Mbarara", "Gulu", "Lira", "Jinja"],
  Ukraine: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Dubai",
    "Sharjah",
    "Ajman",
    "Fujairah",
  ],
  "United Kingdom": [
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "Isle of Man",
  ],
  "United States": ["California", "Texas", "Florida", "New York", "Illinois"],
  Uruguay: ["Montevideo", "Salto", "Paysandú", "Maldonado", "Colonia"],
  Uzbekistan: ["Tashkent", "Samarkand", "Bukhara", "Fergana", "Andijan"],
  Vanuatu: ["Port Vila", "Luganville", "Norsup", "Sola", "Lenakel"],
  "Vatican City": ["Vatican City"],
  Venezuela: [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Ciudad Guayana",
  ],
  Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Haiphong", "Can Tho"],
  Yemen: ["Sana'a", "Aden", "Taiz", "Hudaydah", "Ibb"],
  Zambia: ["Lusaka", "Kitwe", "Ndola", "Livingstone", "Chingola"],
  Zimbabwe: ["Harare", "Bulawayo", "Mutare", "Gweru", "Masvingo"],
};

export const COUNTRY_CODES = {
  Afghanistan: "+93",
  Albania: "+355",
  Algeria: "+213",
  Andorra: "+376",
  Angola: "+244",
  "Antigua and Barbuda": "+1-268",
  Argentina: "+54",
  Armenia: "+374",
  Australia: "+61",
  Austria: "+43",
  Azerbaijan: "+994",
  Bahamas: "+1-242",
  Bahrain: "+973",
  Bangladesh: "+880",
  Barbados: "+1-246",
  Belarus: "+375",
  Belgium: "+32",
  Belize: "+501",
  Benin: "+229",
  Bhutan: "+975",
  Bolivia: "+591",
  "Bosnia and Herzegovina": "+387",
  Botswana: "+267",
  Brazil: "+55",
  Brunei: "+673",
  Bulgaria: "+359",
  "Burkina Faso": "+226",
  Burundi: "+257",
  "Cabo Verde": "+238",
  Cambodia: "+855",
  Cameroon: "+237",
  Canada: "+1",
  "Central African Republic": "+236",
  Chad: "+235",
  Chile: "+56",
  China: "+86",
  Colombia: "+57",
  Comoros: "+269",
  "Congo (Congo-Brazzaville)": "+242",
  "Congo (Democratic Republic of the Congo)": "+243",
  "Costa Rica": "+506",
  Croatia: "+385",
  Cuba: "+53",
  Cyprus: "+357",
  "Czech Republic (Czechia)": "+420",
  Denmark: "+45",
  Djibouti: "+253",
  Dominica: "+1-767",
  "Dominican Republic": "+1-809",
  Ecuador: "+593",
  Egypt: "+20",
  "El Salvador": "+503",
  "Equatorial Guinea": "+240",
  Eritrea: "+291",
  Estonia: "+372",
  Eswatini: "+268",
  Ethiopia: "+251",
  Fiji: "+679",
  Finland: "+358",
  France: "+33",
  Gabon: "+241",
  Gambia: "+220",
  Georgia: "+995",
  Germany: "+49",
  Ghana: "+233",
  Greece: "+30",
  Grenada: "+1-473",
  Guatemala: "+502",
  Guinea: "+224",
  "Guinea-Bissau": "+245",
  Guyana: "+592",
  Haiti: "+509",
  Honduras: "+504",
  Hungary: "+36",
  Iceland: "+354",
  India: "+91",
  Indonesia: "+62",
  Iran: "+98",
  Iraq: "+964",
  Ireland: "+353",
  Israel: "+972",
  Italy: "+39",
  Jamaica: "+1-876",
  Japan: "+81",
  Jordan: "+962",
  Kazakhstan: "+7",
  Kenya: "+254",
  Kiribati: "+686",
  "Korea, North": "+850",
  "Korea, South": "+82",
  Kuwait: "+965",
  Kyrgyzstan: "+996",
  Laos: "+856",
  Latvia: "+371",
  Lebanon: "+961",
  Lesotho: "+266",
  Liberia: "+231",
  Libya: "+218",
  Liechtenstein: "+423",
  Lithuania: "+370",
  Luxembourg: "+352",
  Madagascar: "+261",
  Malawi: "+265",
  Malaysia: "+60",
  Maldives: "+960",
  Mali: "+223",
  Malta: "+356",
  "Marshall Islands": "+692",
  Mauritania: "+222",
  Mauritius: "+230",
  Mexico: "+52",
  Micronesia: "+691",
  Moldova: "+373",
  Monaco: "+377",
  Mongolia: "+976",
  Montenegro: "+382",
  Morocco: "+212",
  Mozambique: "+258",
  Myanmar: "+95",
  Namibia: "+264",
  Nauru: "+674",
  Nepal: "+977",
  Netherlands: "+31",
  "New Zealand": "+64",
  Nicaragua: "+505",
  Niger: "+227",
  Nigeria: "+234",
  "North Macedonia": "+389",
  Norway: "+47",
  Oman: "+968",
  Pakistan: "+92",
  Palau: "+680",
  Panama: "+507",
  "Papua New Guinea": "+675",
  Paraguay: "+595",
  Peru: "+51",
  Philippines: "+63",
  Poland: "+48",
  Portugal: "+351",
  Qatar: "+974",
  Romania: "+40",
  Russia: "+7",
  Rwanda: "+250",
  "Saint Kitts and Nevis": "+1-869",
  "Saint Lucia": "+1-758",
  "Saint Vincent and the Grenadines": "+1-784",
  Samoa: "+685",
  "San Marino": "+378",
  "Sao Tome and Principe": "+239",
  "Saudi Arabia": "+966",
  Senegal: "+221",
  Serbia: "+381",
  Seychelles: "+248",
  "Sierra Leone": "+232",
  Singapore: "+65",
  Slovakia: "+421",
  Slovenia: "+386",
  "Solomon Islands": "+677",
  Somalia: "+252",
  "South Africa": "+27",
  "South Sudan": "+211",
  Spain: "+34",
  "Sri Lanka": "+94",
  Sudan: "+249",
  Suriname: "+597",
  Sweden: "+46",
  Switzerland: "+41",
  Syria: "+963",
  Taiwan: "+886",
  Tajikistan: "+992",
  Tanzania: "+255",
  Thailand: "+66",
  "Timor-Leste": "+670",
  Togo: "+228",
  Tonga: "+676",
  "Trinidad and Tobago": "+1-868",
  Tunisia: "+216",
  Turkey: "+90",
  Turkmenistan: "+993",
  Tuvalu: "+688",
  Uganda: "+256",
  Ukraine: "+380",
  "United Arab Emirates": "+971",
  "United Kingdom": "+44",
  "United States": "+1",
  Uruguay: "+598",
  Uzbekistan: "+998",
  Vanuatu: "+678",
  "Vatican City": "+39-06",
  Venezuela: "+58",
  Vietnam: "+84",
  Yemen: "+967",
  Zambia: "+260",
  Zimbabwe: "+263",
};
