import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";
import ReactQueryClientProvider from "@/utils/client/ReactQueryClientProvider";
import { MessageProvider } from "@/context/MessageContext";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const monaSans = localFont({
  src: "/fonts/Mona-Sans.woff2",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Skool Bag",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body
          className={` ${monaSans.className} antialiased no-scrollbar scrollbar-hide`}
        >
          <ThemeProvider>
            <ReactQueryClientProvider>
              <MessageProvider>{children}</MessageProvider>
            </ReactQueryClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
