import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/theme/theme-provider";
import ReactQueryClientProvider from "@/utils/client/ReactQueryClientProvider";
import { MessageProvider } from "@/context/MessageContext";

const monaSans = localFont({
  src: "/fonts/Mona-Sans.woff2",
  weight: "400",
  style: "normal",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Skool Bag",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${monaSans.className} antialiased no-scrollbar scrollbar-hide`}
      >
        <ThemeProvider>
          <ReactQueryClientProvider>
            <MessageProvider>{children}</MessageProvider>
          </ReactQueryClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
